// tenantService.ts – Service layer for creating tenants with email/password validation
// Uses Supabase Auth for user creation and the landlord schema functions for provisioning

import { supabase, supabaseAdmin } from "./supabase";
import type { Tenant } from "../types";
// Removed unused uuid import

/**
 * Generate a random temporary password (12‑16 characters, alphanumeric).
 */
function generateTempPassword(): string {
    const length = 14;
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let pwd = "";
    for (let i = 0; i < length; i++) {
        pwd += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return pwd;
}

/**
 * Create a new tenant in the landlord schema and provision an isolated schema.
 * Returns the tenant UUID and the temporary password (to be sent by email).
 */
export async function createTenant({
    name,
    slug,
    email,
    plan = "TRIAL",
    type = "full",
    cloudSync = true,
}: {
    name: string;
    slug: string;
    email: string;
    plan?: string;
    type?: "full" | "pos_only";
    cloudSync?: boolean;
}): Promise<{ tenantId: string; tempPassword: string }> {
    // 1️⃣ Generate temporary password
    const tempPassword = generateTempPassword();

    // 2️⃣ Create Supabase Auth user (service role key is required)
    // We ALWAYS create the user so they can login and we can use the Kill Switch (disable account),
    // even if they don't sync data to the cloud (cloudSync = false).
    const { error: authError, data: authUser } = await supabaseAdmin.auth.admin.createUser({
        email,
        password: tempPassword,
        email_confirm: true,
        user_metadata: {
            name,
            full_name: name,
            slug,
            type,
            cloudSync,
            is_new_user: true,
        },
    });

    if (authError) {
        console.error("Supabase user creation failed", authError);
        throw authError;
    }

    // Save the ID in case we need to rollback
    const authUserId = authUser?.user?.id;
    if (!authUserId) {
        throw new Error("Supabase Auth user ID missing after tenant user creation");
    }

    // 3️⃣ Call the provisioning function defined in the landlord schema
    const { data, error: fnError } = await supabaseAdmin.rpc("create_new_tenant", {
        p_name: name,
        p_slug: slug,
        p_email: email,
        p_type: type,
        p_cloud_sync: cloudSync,
    });

    if (fnError) {
        console.error("Tenant provisioning failed", fnError);
        // Rollback auth user if we created one
        if (authUserId) {
            await supabaseAdmin.auth.admin.deleteUser(authUserId);
        }
        throw fnError;
    }

    // 4️⃣ Insert subscription / plan (simplified – could be expanded later)
    const tenantId = data as string; // function returns UUID

    const { error: metadataError } = await supabaseAdmin.auth.admin.updateUserById(authUserId, {
        user_metadata: {
            name,
            full_name: name,
            slug,
            type,
            cloudSync,
            is_new_user: true,
            tenant_id: tenantId,
        },
    });

    if (metadataError) {
        console.error("Failed to sync tenant metadata into Supabase Auth", metadataError);
        throw metadataError;
    }

    const { error: subscriptionError } = await supabaseAdmin.from("subscriptions").insert({
        tenant_id: tenantId,
        plan_name: plan,
        is_active: true,
    });

    if (subscriptionError) {
        console.error("Failed to create tenant subscription", subscriptionError);
        throw subscriptionError;
    }

    // 5️⃣ Send verification email – Supabase automatically sends a magic link if you enable it,
    // but we will trigger a custom email via a server‑side function (placeholder here).
    // In production you would call an email service (SendGrid, Postmark, etc.).
    // await sendVerificationEmail(email, tempPassword);

    return { tenantId, tempPassword };
}

/**
 * Verify a tenant's email using a token generated by an external email service.
 * This is a placeholder – the real implementation lives on the backend.
 */
export async function verifyTenantEmail(token: string): Promise<void> {
    const { error } = await supabaseAdmin.rpc("verify_tenant_email", { p_token: token });
    if (error) throw error;
}

/**
 * Change the temporary password after the user logs in for the first time.
 */
export async function changeTenantPassword(newPassword: string): Promise<void> {
    const { error } = await supabase.auth.updateUser({ password: newPassword });
    if (error) throw error;
}

/**
 * Fetch all real tenants from the landlord.tenants table using the admin client.
 */
export async function getTenants(): Promise<Tenant[]> {
    const { data, error } = await supabaseAdmin
        .from("tenants")
        .select("*")
        .order("created_at", { ascending: false });

    if (error) {
        console.error("Error fetching tenants:", error);
        throw error;
    }
    return data || [];
}

/**
 * Suspend a tenant (Update its verification and status).
 */
export async function suspendTenant(id: string): Promise<void> {
    const { error } = await supabaseAdmin
        .from("tenants")
        .update({
            status: 'SUSPENDED'
        })
        .eq("id", id);
    if (error) throw error;
}

/**
 * Reactivate a tenant.
 */
export async function reactivateTenant(id: string): Promise<void> {
    const { error } = await supabaseAdmin
        .from("tenants")
        .update({
            status: 'ACTIVE'
        })
        .eq("id", id);
    if (error) throw error;
}

export const tenantService = {
    createTenant,
    verifyTenantEmail,
    changeTenantPassword,
    getTenants,
    suspendTenant,
    reactivateTenant,
};
