import { supabase, supabaseAdmin } from "./supabase";
import type { Tenant, TenantTerminalRegistryEntry, TenantTerminalSnapshot, Terminal } from "../types";

export interface DashboardStats {
    activeTenants: number;
    suspendedTenants: number;
    terminals: number;
}

/**
 * Generate a random temporary password (12‑16 characters, alphanumeric).
 */
function generateTempPassword(): string {
    const length = 14;
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let pwd = "";
    for (let i = 0; i < length; i++) {
        pwd += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return pwd;
}

/**
 * Create a new tenant in the landlord schema and provision an isolated schema.
 * Returns the tenant UUID and the temporary password (to be sent by email).
 */
export async function createTenant({
    name,
    slug,
    email,
    plan = "TRIAL",
    type = "full",
    cloudSync = true,
}: {
    name: string;
    slug: string;
    email: string;
    plan?: string;
    type?: "full" | "pos_only";
    cloudSync?: boolean;
}): Promise<{ tenantId: string; tempPassword: string }> {
    // 1) Generate temporary password
    const tempPassword = generateTempPassword();

    // 2) Create Auth user (service role).
    const { error: authError, data: authUser } = await supabaseAdmin.auth.admin.createUser({
        email,
        password: tempPassword,
        email_confirm: true,
        user_metadata: {
            name,
            full_name: name,
            slug,
            type,
            cloudSync,
            is_new_user: true,
        },
    });

    if (authError) {
        console.error("Supabase user creation failed", authError);
        throw authError;
    }

    const authUserId = authUser?.user?.id;
    if (!authUserId) {
        throw new Error("Supabase Auth user ID missing after tenant user creation");
    }

    // 3) Provision tenant schema/records in landlord.
    const { data, error: fnError } = await supabaseAdmin.rpc("create_new_tenant", {
        p_name: name,
        p_slug: slug,
        p_email: email,
        p_type: type,
        p_cloud_sync: cloudSync,
    });

    if (fnError) {
        console.error("Tenant provisioning failed", fnError);
        await supabaseAdmin.auth.admin.deleteUser(authUserId);
        throw fnError;
    }

    const tenantId = data as string;

    // 4) Sync auth metadata with the real tenant ID.
    const { error: metadataError } = await supabaseAdmin.auth.admin.updateUserById(authUserId, {
        user_metadata: {
            name,
            full_name: name,
            slug,
            type,
            cloudSync,
            is_new_user: true,
            tenant_id: tenantId,
        },
    });

    if (metadataError) {
        console.error("Failed to sync tenant metadata into Supabase Auth", metadataError);
        await supabaseAdmin.from("tenants").delete().eq("id", tenantId);
        await supabaseAdmin.auth.admin.deleteUser(authUserId);
        throw metadataError;
    }

    // 5) Create tenant subscription row.
    const { error: subscriptionError } = await supabaseAdmin.from("subscriptions").insert({
        tenant_id: tenantId,
        plan_name: plan,
        is_active: true,
    });

    if (subscriptionError) {
        console.error("Failed to create tenant subscription", subscriptionError);
        await supabaseAdmin.from("tenants").delete().eq("id", tenantId);
        await supabaseAdmin.auth.admin.deleteUser(authUserId);
        throw subscriptionError;
    }

    return { tenantId, tempPassword };
}

/**
 * Verify a tenant's email using a token generated by an external email service.
 * This is a placeholder – the real implementation lives on the backend.
 */
export async function verifyTenantEmail(token: string): Promise<void> {
    const { error } = await supabaseAdmin.rpc("verify_tenant_email", { p_token: token });
    if (error) throw error;
}

/**
 * Change the temporary password after the user logs in for the first time.
 */
export async function changeTenantPassword(newPassword: string): Promise<void> {
    const { error } = await supabase.auth.updateUser({ password: newPassword });
    if (error) throw error;
}

/**
 * Fetch all real tenants from the landlord.tenants table using the admin client.
 */
export async function getTenants(): Promise<Tenant[]> {
    const { data, error } = await supabaseAdmin
        .from("tenants")
        .select("*")
        .order("created_at", { ascending: false });

    if (error) {
        console.error("Error fetching tenants:", error);
        throw error;
    }
    return (data as Tenant[]) || [];
}

export async function updateTenantTaxId(id: string, taxId: string): Promise<void> {
    const { error } = await supabaseAdmin
        .from("tenants")
        .update({ tax_id: taxId })
        .eq("id", id);

    if (error) throw error;
}

export async function updateTenant(
    id: string,
    payload: {
        name: string;
        legal_name: string | null;
        tax_id: string | null;
        phone: string | null;
        type: "full" | "pos_only";
        cloud_sync: boolean;
    },
): Promise<void> {
    const { error } = await supabaseAdmin
        .from("tenants")
        .update(payload)
        .eq("id", id);

    if (error) throw error;
}

export async function getDashboardStats(): Promise<DashboardStats> {
    const [tenantsRes, terminalsRes] = await Promise.all([
        supabaseAdmin.from("tenants").select("status"),
        supabaseAdmin.schema("public").from("terminals").select("id", { count: "exact", head: true }),
    ]);

    if (tenantsRes.error) throw tenantsRes.error;
    if (terminalsRes.error) throw terminalsRes.error;

    const activeTenants = tenantsRes.data?.filter(
        (tenant) => tenant.status === "ACTIVE" || tenant.status === "TRIAL",
    ).length || 0;
    const suspendedTenants = tenantsRes.data?.filter(
        (tenant) => tenant.status === "SUSPENDED",
    ).length || 0;

    return {
        activeTenants,
        suspendedTenants,
        terminals: terminalsRes.count || 0,
    };
}

/**
 * Suspend a tenant (update status).
 */
export async function suspendTenant(id: string): Promise<void> {
    const { error } = await supabaseAdmin
        .from("tenants")
        .update({ status: "SUSPENDED" })
        .eq("id", id);
    if (error) throw error;
}

/**
 * Reactivate a tenant.
 */
export async function reactivateTenant(id: string): Promise<void> {
    const { error } = await supabaseAdmin
        .from("tenants")
        .update({ status: "ACTIVE" })
        .eq("id", id);
    if (error) throw error;
}

export async function getTenantTerminalOverview(tenantId: string): Promise<TenantTerminalSnapshot[]> {
    const [terminalsRes, registryRes] = await Promise.all([
        supabaseAdmin
            .schema("public")
            .from("terminals")
            .select("id,tenant_id,device_token,name,is_active,last_checkin_at,created_at")
            .eq("tenant_id", tenantId)
            .order("created_at", { ascending: true }),
        supabaseAdmin
            .from("tenant_server_registry")
            .select("*")
            .eq("tenant_id", tenantId)
            .order("last_seen_at", { ascending: false }),
    ]);

    if (terminalsRes.error) {
        throw terminalsRes.error;
    }

    let registryRows: TenantTerminalRegistryEntry[] = [];
    if (registryRes.error) {
        const code = (registryRes.error as { code?: string }).code;
        if (code !== "42P01") {
            throw registryRes.error;
        }
    } else {
        registryRows = (registryRes.data as TenantTerminalRegistryEntry[]) || [];
    }

    const registryByTerminalId = new Map<string, TenantTerminalRegistryEntry>();
    const registryByDeviceId = new Map<string, TenantTerminalRegistryEntry>();
    const matchedRegistryIds = new Set<string>();

    for (const row of registryRows) {
        if (row.terminal_id && !registryByTerminalId.has(row.terminal_id)) {
            registryByTerminalId.set(row.terminal_id, row);
        }
        if (row.device_id && !registryByDeviceId.has(row.device_id)) {
            registryByDeviceId.set(row.device_id, row);
        }
    }

    const snapshots: TenantTerminalSnapshot[] = ((terminalsRes.data as Terminal[]) || []).map((terminal) => {
        const registry = registryByTerminalId.get(terminal.id) || registryByDeviceId.get(terminal.device_token) || null;
        if (registry?.id) {
            matchedRegistryIds.add(registry.id);
        }

        return {
            id: terminal.id,
            tenant_id: terminal.tenant_id,
            terminal_id: terminal.id,
            name: terminal.name || terminal.id,
            device_token: terminal.device_token,
            is_active: Boolean(terminal.is_active),
            last_checkin_at: terminal.last_checkin_at || null,
            created_at: terminal.created_at || null,
            registry,
        };
    });

    for (const row of registryRows) {
        if (matchedRegistryIds.has(row.id)) continue;

        snapshots.push({
            id: row.id,
            tenant_id: row.tenant_id,
            terminal_id: row.terminal_id || null,
            name: row.terminal_name || row.terminal_id || row.device_id || "Terminal sin catálogo",
            device_token: row.device_id || null,
            is_active: (row.status || "").toUpperCase() === "ONLINE",
            last_checkin_at: row.last_seen_at || null,
            created_at: row.created_at || null,
            registry: row,
        });
    }

    return snapshots;
}

export const tenantService = {
    createTenant,
    verifyTenantEmail,
    changeTenantPassword,
    getTenants,
    updateTenantTaxId,
    updateTenant,
    getDashboardStats,
    suspendTenant,
    reactivateTenant,
    getTenantTerminalOverview,
};
