begin;

create table if not exists landlord.internal_work_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  request_type text not null check (request_type in ('problem', 'improvement')),
  product text not null check (product in ('msmall', 'clicpos', 'erp', 'cloud-admin', 'general')),
  priority text not null default 'Media' check (priority in ('Baja', 'Media', 'Alta', 'Critica')),
  status text not null default 'new' check (status in ('new', 'under_review', 'in_progress', 'completed', 'rejected')),
  title text not null,
  description text not null,
  source_page text,
  reported_by uuid references landlord.cloud_admin_users(id) on delete set null,
  assigned_to uuid references landlord.cloud_admin_users(id) on delete set null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  completed_at timestamptz
);

create index if not exists internal_work_requests_status_priority_idx
  on landlord.internal_work_requests (status, priority, updated_at desc);
create index if not exists internal_work_requests_product_idx
  on landlord.internal_work_requests (product, updated_at desc);
create index if not exists internal_work_requests_reported_by_idx
  on landlord.internal_work_requests (reported_by);
create index if not exists internal_work_requests_assigned_to_idx
  on landlord.internal_work_requests (assigned_to);

drop trigger if exists update_internal_work_requests_updated_at on landlord.internal_work_requests;
create trigger update_internal_work_requests_updated_at
before update on landlord.internal_work_requests
for each row execute function landlord.update_support_updated_at_column();

alter table landlord.internal_work_requests enable row level security;
revoke all on landlord.internal_work_requests from anon, authenticated;
grant select, insert, update on landlord.internal_work_requests to service_role;

commit;
